# Generated by Django 3.0.6 on 2020-09-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosclientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Direcc', models.CharField(max_length=35)),
                ('DireccFact', models.CharField(max_length=40)),
                ('Facturaranombrede', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Datosclient',
        ),
    ]
