# Generated by Django 3.0.6 on 2020-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200907_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosclientes',
            name='comprobantep',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
