# Generated by Django 3.0.6 on 2020-09-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_datosclientes_comprobantep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosclientes',
            name='comprobantep',
        ),
    ]
