# Generated by Django 3.0.6 on 2020-09-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_datosclientes_comprobantep'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosclientes',
            name='Docnro',
            field=models.IntegerField(default=0),
        ),
    ]
