# Generated by Django 3.0.6 on 2020-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_datosclientes_docnro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclientes',
            name='Docnro',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='datosclientes',
            name='comprobantep',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
