# Generated by Django 3.0.6 on 2020-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20200909_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosclientes',
            name='compago',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
