# Generated by Django 3.0.6 on 2020-09-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_datosclientes_compago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosclientes',
            name='comprobantep',
        ),
    ]
