# Generated by Django 3.0.6 on 2020-09-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_datosclientes_comprobantep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosclientes',
            name='compago',
        ),
        migrations.AddField(
            model_name='datosclientes',
            name='comprobantep',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
