# Generated by Django 3.0.6 on 2020-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_auto_20200909_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclientes',
            name='Docnro',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='datosclientes',
            name='comprobantep',
            field=models.FileField(upload_to='images/'),
        ),
    ]
