# Generated by Django 3.0.6 on 2020-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20200909_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosclientes',
            name='comprobantep',
            field=models.FileField(upload_to='images/'),
        ),
    ]
